# SOPS configuration
# See: https://github.com/Mic92/sops-nix

# To set up:
# 1. Generate age key: mkdir -p ~/.config/sops/age && age-keygen -o ~/.config/sops/age/keys.txt
# 2. Get public key: age-keygen -y ~/.config/sops/age/keys.txt
# 3. Add public key below
# 4. Create secrets: sops secrets/secrets.yaml

keys:
  # Add your age public keys here (one per machine)
  # Format: age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - &gfoster_wsl_debian age1m0ye9zusm48tf6k34ty833qxnn3rxtqe9cdekm9ejanq0m4e85ls8jsd79
  - &gfoster_wsl_nix age1rdhwvz3tt4rs05e3lns4ey5g2n20c7m49ulplvt4v5gvymjjafsquykn9y

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *gfoster_wsl_debian
          - *gfoster_wsl_nix
          # Add more keys for other machines
