;;; init.el --- vanilla Emacs, hand-built -*- lexical-binding: t; -*-

;; Phase 1 scaffold.  Deliberately small: enough to open files, complete, edit
;; with evil, and run magit -- so that `emacsclient -s vanilla' is a real editor
;; and the daemon/socket plumbing can be tested.  Org, gcal, LilyPond and the
;; Claude integration land in later phases and are NOT here yet; Doom remains
;; the daily driver until they are.
;;
;; FLOOR: Emacs 30.  Linux gets emacs-unstable (31.x) and both Macs get 30.2,
;; because emacs-overlay publishes no darwin binaries and building 31 from
;; source there is an hour on the least-tested stdenv.  So anything 31-only
;; will build fine and then fail on the Macs -- keep to 30 APIs until the Intel
;; Mac question is resolved.
;;
;; Packages come from Nix (see ../package.nix).  Nothing here may fetch.

;;; Code:

(when (< emacs-major-version 30)
  (error "This config targets Emacs 30+; running %s" emacs-version))

(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

;; lisp/my-nix-paths.el is GENERATED by ../package.nix and is the only file
;; under lisp/ that is not in git: it holds the store paths this config cannot
;; hand-write, because they change on every rebuild -- GNU diff, for
;; claude-diff.
;;
;; SOFT require, and that is not defensiveness for its own sake.
;; `my.emacs.vanilla.manageConfig = false' hands ~/.config/emacs to a plain
;; working copy for heavy iteration, and that copy has no generated file in it.
;; Every consumer reads these constants through `bound-and-true-p' and falls
;; back to an `exec-path' lookup, so the only thing lost in that mode is
;; reproducibility -- which is the point of that mode.
(require 'my-nix-paths nil t)

;; no-littering must load before the packages whose paths it retargets.
;; Its two directory variables are set in early-init.el.
(require 'no-littering)
(no-littering-theme-backups)
(load custom-file :noerror :nomessage)

(require 'use-package)

;; --- Emacs itself ----------------------------------------------------------

(use-package emacs
  :demand t
  :init
  (setq enable-recursive-minibuffers t
        read-extended-command-predicate #'command-completion-default-include-p
        minibuffer-prompt-properties
        '(read-only t cursor-intangible t face minibuffer-prompt)
        ;; TAB completes when already indented -- the hook corfu needs.
        tab-always-indent 'complete
        ;; Emacs 30: drop the ispell capf out of text modes.  It queries the
        ;; spell process on every completion and is rarely what is wanted.
        text-mode-ispell-word-completion nil
        sentence-end-double-space nil
        require-final-newline t
        create-lockfiles nil
        use-short-answers t
        ring-bell-function #'ignore
        ;; TRAMP hosts must not be able to hang session restore.
        remote-file-name-access-timeout 5)
  (setq-default indent-tabs-mode nil
                fill-column 80)
  :config
  (savehist-mode 1)          ; load-bearing: vertico sorts by history position
  (recentf-mode 1)
  (save-place-mode 1)
  (global-so-long-mode 1)    ; off by default; long lines otherwise wedge Emacs
  (repeat-mode 1)
  (electric-pair-mode 1)
  (show-paren-mode 1)
  (column-number-mode 1)
  (setq display-line-numbers-type t)
  (add-hook 'prog-mode-hook #'display-line-numbers-mode))

;; --- Discoverability -------------------------------------------------------
;;
;; which-key is what makes the SPC leader a MENU rather than a set of chords
;; you have to remember, so it gets a real configuration block rather than one
;; `(which-key-mode 1)' buried in the `emacs' block above.
;;
;; BUILT IN since Emacs 30 -- `(locate-library "which-key")' in this build
;; returns .../emacs-30.2/share/emacs/30.2/lisp/which-key.elc, not an elpa
;; path. It is deliberately NOT in package.nix: a MELPA copy would land earlier
;; on load-path and shadow the built-in with a fork that has drifted.
(use-package which-key
  :demand t
  :init
  ;; `setopt', NOT `setq'. `which-key-dont-use-unicode' carries a :set function
  ;; that re-evaluates `which-key-separator' and `which-key-ellipsis' from
  ;; their standard values, and those standard values are what read the flag.
  ;; Measured in this build:
  ;;
  ;;   (setq   which-key-dont-use-unicode nil) -> separator " : ", ellipsis ".."
  ;;   (setopt which-key-dont-use-unicode nil) -> separator " U+2192 ",
  ;;                                              ellipsis U+2026
  ;;
  ;; i.e. a plain `setq' flips the flag and silently keeps the ASCII glyphs,
  ;; which looks like which-key ignoring the setting.
  (setopt which-key-dont-use-unicode nil)
  (setq which-key-idle-delay 0.3           ; menu appears rather than waits
        which-key-idle-secondary-delay 0.05 ; ...and instantly for the next key
        which-key-max-description-length 40 ; default 27 truncates real names
        which-key-add-column-padding 1
        which-key-min-display-lines 6       ; stop the popup jumping in height
        which-key-show-remaining-keys t
        ;; Alphabetical, not by key-type: a menu you read top-to-bottom.
        which-key-sort-order #'which-key-key-order-alpha
        which-key-prefix-prefix "+"
        which-key-show-prefix 'echo         ; keys so far go in the echo area
        which-key-popup-type 'side-window
        which-key-side-window-location 'bottom
        which-key-side-window-max-height 0.30
        which-key-preserve-window-configuration t
        ;; LOAD-BEARING, and the default is wrong HERE specifically. Its
        ;; defcustom value is `(not (display-graphic-p))', EVALUATED AT LOAD
        ;; TIME. This is a daemon: at load there is no frame, `display-graphic-p'
        ;; is nil, so the default computes to t and stays t forever -- including
        ;; in the GUI frames emacsclient makes later. Measured: t in a daemon
        ;; started from the store config. The imprecise fit rounds the popup to
        ;; whole lines and clips the last row of a full menu.
        which-key-allow-imprecise-window-fit nil)
  :config
  ;; NOTE: `which-key-mode' sets `prefix-help-command' to
  ;; `which-key-C-h-dispatch'. The `embark' block below then sets it to
  ;; `embark-prefix-help-command' in its `:init', which runs LATER, so EMBARK
  ;; WINS -- verified in a running daemon, where `prefix-help-command' is
  ;; `embark-prefix-help-command'. That is the intended outcome and not an
  ;; accident of ordering: embark's version offers a searchable completing-read
  ;; over the prefix's keys WITH their descriptions, which is the same "find it
  ;; by name" property this whole file exists for. The idle popup is unaffected;
  ;; only what `C-h' after a prefix does changes.
  (which-key-mode 1))

;; --- Appearance ------------------------------------------------------------
;;
;; The font is applied twice on purpose.  This is a DAEMON: at init there is no
;; frame, so set-face-attribute alone applies to nothing, and every frame made
;; later by emacsclient needs it again.  Doom papered over this by re-applying
;; `doom-font' per frame; there is no vanilla equivalent, so we do it by hand.
(defconst my/font-family "VictorMono Nerd Font")
(defconst my/font-height 180)           ; 1/10 pt, i.e. Doom's :size 18

(defun my/apply-font (&optional frame)
  "Apply the default face to FRAME, or to the current frame."
  (when (display-graphic-p frame)
    (set-face-attribute 'default frame
                        :family my/font-family :height my/font-height)))

(add-to-list 'default-frame-alist
             (cons 'font (format "%s-%d" my/font-family (/ my/font-height 10))))
(add-hook 'after-make-frame-functions #'my/apply-font)
(my/apply-font)

(setq nerd-icons-font-family "Symbols Nerd Font Mono")

;; Italic syntax faces, re-applied on every theme load.
;;
;; Doom's `custom-set-faces!' hooked doom-customize-theme-hook, which is the
;; ONLY reason these survived `load-theme' running afterwards.  Emacs 29+
;; `enable-theme-functions' is the exact analogue.  Without it a naive port
;; silently loses the italics the moment the theme loads.
(defun my/italicize-syntax-faces (&optional _theme)
  "Italicise comment, keyword, string and docstring faces."
  (dolist (face '(font-lock-comment-face
                  font-lock-keyword-face
                  font-lock-string-face
                  font-lock-doc-face))
    (set-face-attribute face nil :slant 'italic)))
(add-hook 'enable-theme-functions #'my/italicize-syntax-faces)

(use-package doom-themes
  :demand t
  :config
  (load-theme 'doom-gruvbox t)
  (my/italicize-syntax-faces))

(use-package doom-modeline
  :demand t
  :config (doom-modeline-mode 1))

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

(use-package hl-todo
  :demand t
  :config (global-hl-todo-mode 1))

;; --- Completion ------------------------------------------------------------

(use-package vertico
  :demand t
  :config (vertico-mode 1))

;; `SPC '' -- Doom's "resume last search". Its own file (vertico-repeat.el), so
;; the same rule as the consult sub-packages applies.
;;
;; `vertico-repeat-save' is the half that is easy to miss: without it on
;; `minibuffer-setup-hook' nothing ever records a session and `vertico-repeat'
;; errors with "No repeatable session". It is a plain function, not a command,
;; hence `:autoload'; and it MUST have an autoload stub, because a void
;; function on `minibuffer-setup-hook' would break every minibuffer prompt in
;; the session, not just this key.
(use-package vertico-repeat
  :commands (vertico-repeat vertico-repeat-select)
  :autoload (vertico-repeat-save)
  :init (add-hook 'minibuffer-setup-hook #'vertico-repeat-save))

(use-package orderless
  :demand t
  :init
  ;; completion-category-defaults must be nil.  Packages -- eglot among them --
  ;; append their own category defaults at load time, and those silently
  ;; override completion-styles.  This is why "orderless does nothing in my LSP
  ;; buffers" is the perennial bug report.
  (setq completion-styles '(orderless basic)
        completion-category-overrides '((file (styles partial-completion)))
        completion-category-defaults nil))

(use-package marginalia
  :demand t
  :config (marginalia-mode 1))

;; BEFORE the consult block, and that is load-bearing rather than tidy.
;; consult-xref lives in its own file (consult-xref.el), which nothing loads --
;; see the block below the consult one for the general form of this trap. What
;; makes THIS one order-sensitive is that consult's `:config' passes
;; consult-xref to `consult-customize', and `consult--customize-put' silently
;; drops any symbol failing `functionp' with "neither a command nor a source".
;; With this form after the consult block that warning fired on every startup.
(use-package consult-xref
  :autoload (consult-xref))

(use-package consult
  :demand t
  :init
  (setq register-preview-delay 0.5
        register-preview-function #'consult-register-format
        xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref
        completion-in-region-function #'consult-completion-in-region)
  :config
  ;; Default preview-key is 'any: every candidate change opens a file.  For the
  ;; file-touching commands that means one visit per keystroke, so debounce
  ;; them.  NOTE: wrapping any of these in your own command means adding YOUR
  ;; command here too -- consult-customize keys on the command symbol.
  ;; The my/search-* wrappers in my-bindings.el need the same debounce -- but
  ;; they CANNOT be listed here. `consult--customize-put' tests `functionp' as
  ;; this `:config' runs, which is long before lisp/ is loaded, so all three
  ;; were warned about and dropped. That call lives next to the defuns instead.
  (consult-customize
   consult-ripgrep consult-git-grep consult-grep
   consult-bookmark consult-recent-file consult-xref
   :preview-key '(:debounce 0.4 any)))

;; consult ships as SEVEN files, and only consult.el is what `:demand t' above
;; loads. Everything else -- consult-imenu, consult-flymake, consult-org,
;; consult-register, consult-xref -- is a separate feature that nothing loads,
;; because early-init.el turns package.el activation (and therefore every
;; package autoload file) off. Without a form per file the leader keys resolve
;; to the symbol and then fail with void-function on the keypress.
;;
;; Each must be its OWN `use-package'. A `:commands' entry in the consult block
;; emits (autoload SYM "consult" ...), naming the ENCLOSING package's file --
;; the wrong file for every one of these.
(use-package consult-imenu
  :commands (consult-imenu consult-imenu-multi))

(use-package consult-flymake
  :commands (consult-flymake))

(use-package consult-org
  :commands (consult-org-heading consult-org-agenda))

;; `:autoload' rather than `:commands' for the two non-interactive ones:
;; `consult-register-format' and `consult-register-window' are wired into
;; `register-preview-function'/`register-preview-delay' in the consult block
;; above, so they are CALLED without ever being a command. `:commands' would
;; declare them interactive, which they are not.
(use-package consult-register
  :commands (consult-register consult-register-load consult-register-store)
  :autoload (consult-register-format consult-register-window))

(use-package embark
  :demand t
  :init (setq prefix-help-command #'embark-prefix-help-command))

(use-package embark-consult
  :demand t
  :after (embark consult))

(use-package corfu
  :demand t
  :init
  ;; Manual completion, on TAB, rather than an auto-popup: with orderless in
  ;; play an auto-popup fires on nearly every keystroke.  Ambient hinting comes
  ;; from completion-preview-mode below instead.
  (setq corfu-auto nil
        corfu-cycle t
        corfu-quit-no-match 'separator)
  :config (global-corfu-mode 1))

(use-package cape
  :demand t
  :init
  (add-hook 'completion-at-point-functions #'cape-file)
  (add-hook 'completion-at-point-functions #'cape-dabbrev))

;; Built in since Emacs 30: one inline greyed candidate.  Complements corfu
;; (ranked popup, on demand) rather than replacing it.
(when (fboundp 'global-completion-preview-mode)
  (global-completion-preview-mode 1))

;; --- Modal editing ---------------------------------------------------------

(use-package evil
  :demand t
  :init
  ;; These must be set BEFORE evil loads.  Values copied from Doom's evil
  ;; module so the muscle memory carries over unchanged.
  (setq evil-want-keybinding nil        ; required by evil-collection
        evil-want-C-g-bindings t
        evil-want-C-i-jump nil
        evil-want-C-u-scroll t
        evil-want-C-u-delete t
        evil-want-C-w-delete t
        evil-want-Y-yank-to-eol t
        evil-respect-visual-line-mode nil
        evil-undo-system 'undo-redo     ; built in since Emacs 28
        evil-symbol-word-search t
        evil-ex-search-vim-style-regexp t
        evil-ex-visual-char-range t
        evil-ex-interactive-search-highlight 'selected-window
        evil-kbd-macro-suppress-motion-error t
        evil-mode-line-format nil)
  :config
  (evil-select-search-module 'evil-search-module 'evil-search)
  (evil-mode 1))

(use-package evil-collection
  :demand t
  :after evil
  :config (evil-collection-init))

(use-package evil-surround
  :demand t
  :after evil
  :config (global-evil-surround-mode 1))

;; --- Leader ----------------------------------------------------------------
;;
;; general.el rather than evil's own `evil-set-leader'.  The difference is not
;; syntax: evil's auxiliary keymaps outrank the global state maps, and
;; evil-collection binds SPC in many read-only modes (magit, dired, help, info,
;; pdf-view).  A plain evil-set-leader leader is therefore shadowed in exactly
;; the buffers a Doom user expects it to work in.  `:keymaps 'override' is a
;; pre-built evil INTERCEPT map, which outranks those.
(use-package general
  :demand t
  :init
  (setq general-override-states
        '(insert emacs hybrid normal visual motion operator replace))
  :config
  (general-create-definer my/leader
    :states '(normal insert visual motion emacs)
    :keymaps 'override
    :prefix "SPC"
    :global-prefix "C-SPC")             ; reachable from insert/emacs state

  (general-create-definer my/local-leader
    :states '(normal insert visual motion emacs)
    :keymaps 'override
    :prefix "SPC m"
    :global-prefix "C-SPC m"))

;; The bindings themselves are in lisp/my-bindings.el, required at the bottom
;; of this file. They are NOT here, because `my/leader' does not exist until
;; the `general' block above has finished its `:config' -- and because the map
;; is now long enough that mixing it in with package setup would hide both.

;; --- Version control -------------------------------------------------------

(use-package magit
  ;; magit-blame-addition, magit-file-dispatch and the forge commands are all
  ;; named by the leader map and were all VOID at startup before this list
  ;; grew: magit's own autoload file is never loaded (see early-init.el).
  ;;
  ;; These are safe as `:commands' on the `magit' package even though several
  ;; live in other files -- magit.el `require's magit-blame, magit-files and
  ;; the rest at load time, so (autoload SYM "magit") does define them. That
  ;; is NOT true of the consult sub-packages above, which have no such parent
  ;; require; the difference is why those get a form each and these do not.
  :commands (magit-status
             magit-status-here
             magit-dispatch
             magit-file-dispatch
             magit-blame-addition
             magit-branch-checkout
             magit-branch-and-checkout
             magit-clone
             magit-commit-create
             magit-commit-fixup
             magit-fetch
             magit-file-delete
             magit-find-file
             magit-find-git-config-file
             magit-init
             magit-list-repositories
             magit-list-submodules
             magit-log-buffer-file
             magit-show-commit
             magit-stage-buffer-file
             magit-unstage-buffer-file)
  :init (setq magit-define-global-key-bindings nil))

;; NO `:after magit', for exactly the reason the org-gcal block spells out:
;; `:after' wraps the WHOLE form -- `:commands' included -- in a
;; `with-eval-after-load', so the autoload stubs are deferred too and every
;; forge command stays void until something else loads magit. MEASURED in a
;; cold daemon with `:after magit' present: all 13 forge commands below were
;; unbound while `SPC g '' happily reported `forge-dispatch'.
;;
;; Ordering was never at risk: forge.el opens with (require 'magit) and pulls
;; forge-commands/forge-topics itself, so (autoload SYM "forge") lands
;; everything in the right order.
(use-package forge
  :commands (forge-dispatch
             forge-browse-commit
             forge-browse-issue
             forge-browse-issues
             forge-browse-pullreq
             forge-browse-pullreqs
             forge-browse-remote
             forge-create-issue
             forge-create-pullreq
             forge-list-issues
             forge-list-notifications
             forge-list-pullreqs
             forge-visit-issue
             forge-visit-pullreq))

;; No `:commands' needed for the hunk motions: `:demand t' loads diff-hl.el and
;; diff-hl-next-hunk/-previous-hunk/-revert-hunk/-stage-dwim all live in it.
(use-package diff-hl
  :demand t
  :config
  (global-diff-hl-mode 1)
  (add-hook 'magit-pre-refresh-hook  #'diff-hl-magit-pre-refresh)
  (add-hook 'magit-post-refresh-hook #'diff-hl-magit-post-refresh))

;; Own file again (diff-hl-show-hunk.el), so `SPC g p' needs its own form.
(use-package diff-hl-show-hunk
  :commands (diff-hl-show-hunk))

;; --- Language tooling ------------------------------------------------------
;;
;; eglot and flymake are built in, but "built in" does not mean "bound": only
;; the entry points carry autoload cookies in Emacs's own loaddefs. The `SPC c'
;; keys below were all void at startup without this.
(use-package eglot
  :commands (eglot
             eglot-code-actions
             eglot-find-declaration
             eglot-find-implementation
             eglot-find-typeDefinition
             eglot-format
             eglot-reconnect
             eglot-rename
             eglot-shutdown))

;; compile.el carries an autoload cookie on `compile' but NOT on `recompile',
;; so `SPC c C' was void while `SPC c c' worked -- a good illustration of why
;; "it is built in" is not the same as "it is bound".
(use-package compile
  :commands (compile recompile))

(use-package flymake
  :commands (flymake-mode
             flymake-goto-next-error
             flymake-goto-prev-error
             flymake-show-buffer-diagnostics
             flymake-show-project-diagnostics))

;; --- Editing / navigation --------------------------------------------------

(use-package vundo :commands (vundo))
(use-package avy   :commands (avy-goto-char-timer avy-goto-line))

(use-package envrc
  :demand t
  :config (envrc-global-mode 1))

(use-package ws-butler
  :hook (prog-mode . ws-butler-mode))

;; --- Language tooling, continued -------------------------------------------
;; treesit and project.el are built in. The mode/grammar/eglot wiring is
;; lisp/my-lang.el, required at the bottom of this file -- it is long enough
;; that inlining it here would hide both it and the package setup above.

;; --- Modules ---------------------------------------------------------------
;; Loaded LAST on purpose: everything under lisp/ binds keys through the
;; `my/leader' definer, which does not exist until the `general' block above
;; has finished its :config.
;;
;; my-bindings.el goes after my-org.el: it names org commands, and my-org.el is
;; what emits their autoload stubs and sets `org-directory'.

(require 'my-org)
;; my-lang.el before my-bindings.el: `SPC c' names eglot and flymake commands
;; and my-lang.el is what decides which buffers ever start a server. Neither
;; file binds a key the other defines, so this order is about reading it in the
;; sequence it takes effect, not about correctness.
(require 'my-lang)
;; my-claude.el LOADS claude-diff.el eagerly -- the PermissionRequest hook
;; `--eval's into a daemon that may never have touched claude-code.el.
(require 'my-claude)
(require 'my-bindings)

(provide 'init)
;;; init.el ends here
