{
  runCommand,
  writeText,
  stdenv,
  emacs,
  diffutils,
  # NULL-ABLE ON PURPOSE, and defaulted to null so a caller that has no
  # lilypond at all still evaluates. See `lilypondPkg' below for when it is
  # forced to null regardless of what the caller passed.
  lilypond ? null,
}: let
  # Base Emacs: pkgs.emacs (30.2) on EVERY platform, deliberately.
  #
  # emacs-overlay offers emacs-unstable (31.x), and on Linux it is cached. But
  # taking it only on Linux introduces a version skew across the fleet on day
  # one -- anything 31-only would build and then fail on the Macs, which is the
  # worst kind of bug to have while a config is still being written. And taking
  # it on darwin is not an option: emacs-overlay's hydraJobs cover x86_64-linux
  # and aarch64-linux ONLY, so emacs-unstable on either Mac is an uncached
  # source build (srcRepo = true, so autogen.sh + autoconf) -- on the Intel
  # Mac's 26.05 stdenv that is the least-tested build path in the tree.
  #
  # Emacs 31.1 releases 2026-08-24. Moving to it is a deliberate one-line
  # change here, made once, after the config is stable and the Intel Mac's
  # future is settled.
  baseEmacs = emacs;

  # darwin gets lilypond from HOMEBREW: home/common.nix appends the nix package
  # to home.packages only when `!isDarwin`. Referencing pkgs.lilypond here on a
  # Mac would pull a whole second lilypond into the closure -- one the user does
  # not run and that home/common.nix went out of its way not to install. Nix is
  # lazy, so nulling it here means `lilypond` is never forced on darwin and no
  # build is attempted.
  #
  # The elisp then falls back to probing the lilypond on PATH; see
  # config/lisp/my-lilypond.el, which is written for BOTH cases and for the
  # 2.24-vs-2.26 symbol rename that comes with them.
  lilypondPkg =
    if stdenv.hostPlatform.isDarwin
    then null
    else lilypond;

  optPath = pkg: sub:
    if pkg == null
    then "nil"
    else ''"${pkg}/${sub}"'';

  # GENERATED elisp: the store paths this config needs and cannot hand-write,
  # because they change on every rebuild.
  #
  # It is DATA and (almost) nothing else -- one constant per external program,
  # `nil' where the platform does not get that program from Nix. Keeping the
  # generated surface to one screen of constants is deliberate: generated code
  # is the code nobody reviews, so there must be as little of it as possible
  # and every decision must live in a tracked .el file instead.
  nixPaths = writeText "my-nix-paths.el" ''
    ;;; my-nix-paths.el --- store paths, written at build time -*- lexical-binding: t; -*-

    ;;; Commentary:

    ;; GENERATED by modules/emacs/vanilla/package.nix.  DO NOT EDIT: the copy in
    ;; ~/.config/emacs is a link into the store and every `hms' replaces it.
    ;;
    ;; A constant is nil when this platform does not get that program from Nix.
    ;; darwin is the case that matters -- lilypond comes from Homebrew there --
    ;; and every consumer of these constants is written to fall back to a PATH
    ;; lookup rather than to fail.

    ;;; Code:

    (defconst my/nix-diff-executable ${optPath diffutils "bin/diff"}
      "Absolute path to GNU diff, or nil.
    `claude-diff' shells out to `diff -u'; without this it would silently use
    whatever /usr/bin/diff happens to be -- BSD diff on a Mac -- which is an
    undeclared dependency of a feature that is otherwise fully reproducible.")

    (defconst my/nix-lilypond-executable ${optPath lilypondPkg "bin/lilypond"}
      "Absolute path to the Nix lilypond, or nil on darwin (Homebrew).")

    (defconst my/nix-lilypond-site-lisp ${optPath lilypondPkg "share/emacs/site-lisp"}
      "Directory holding lilypond-mode.el, or nil on darwin (Homebrew).
    The elisp ships INSIDE the lilypond derivation; it is not an
    `emacsPackages' attribute and it is not on MELPA, so there is no other way
    to put it on `load-path'.")

    (provide 'my-nix-paths)
    ;;; my-nix-paths.el ends here
  '';

  # The elisp tree as a store path. The module links a COPY of this into
  # $XDG_CONFIG_HOME/emacs with recursive = true; the store path itself is used
  # directly only by `nix run .#emacs-vanilla`, which is precisely the test
  # that early-init.el has redirected every writable path out of the config
  # directory.
  configDir = runCommand "emacs-vanilla-config" {} ''
    mkdir -p $out
    cp -r ${./config}/. $out/
    # `cp -r' from a store path copies its permissions too, and store
    # directories are r-xr-xr-x -- so writing the generated file INTO the
    # copied lisp/ fails with "Permission denied" until this chmod. (The build
    # only started failing when the first generated file was added; before
    # that nothing ever wrote into the copy.)
    chmod -R u+w $out
    cp ${nixPaths} $out/lisp/my-nix-paths.el
  '';

  # Package set: an EXPLICIT list, deliberately NOT
  # emacsWithPackagesFromUsePackage.
  #
  # emacs-overlay's README: "Config files cannot contain unicode characters,
  # since they're being parsed in nix, which lacks unicode support." The elisp
  # here uses box-drawing section rules and the Doom config we are porting from
  # is full of them. Stripping characters to satisfy a build tool would be the
  # tail wagging the dog, and a silent mis-parse is worse than a manual list.
  #
  # Nothing here may fetch at runtime: early-init.el sets
  # package-enable-at-startup nil and neuters use-package's ensure function.
  withPkgs = baseEmacs.pkgs.withPackages (epkgs:
    with epkgs; [
      # -- infrastructure ---------------------------------------------------
      use-package # built in since 29; pinned so the version is explicit
      no-littering # keeps writable state out of the read-only config dir
      compat # hard dependency of the minad/oantolin packages

      # -- completion -------------------------------------------------------
      vertico
      orderless
      marginalia
      consult
      embark
      embark-consult
      corfu
      cape

      # -- modal editing ----------------------------------------------------
      evil
      evil-collection
      evil-surround
      general # for :keymaps 'override -- a prebuilt evil intercept map

      # -- org ---------------------------------------------------------------
      # org is not listed here, but it is NOT the bundled 9.7 either: org-gcal
      # depends on org, so the ELPA build (9.8.9) comes in transitively and
      # wins the load-path over Emacs 30.2's bundled copy. That is checked, not
      # assumed -- and it is the version we want, because the Doom daemon we
      # are porting from runs 9.8.7. Listing `org' explicitly would pin the
      # same thing twice and make the two disagree the day one moves.
      evil-org # org motions/folding under evil, from Doom's :lang org
      org-gcal # pulls org, oauth2-auto, request-deferred, persist

      # -- Claude Code ------------------------------------------------------
      #
      # yuya373/claude-code-emacs -- the SAME package the Doom daemon runs.
      # Doom's packages.el names a `:recipe' pointing at stevemolitor's fork,
      # but nix-doom-emacs-unstraightened ignores `:recipe' entirely, so Doom
      # has always been running the MELPA/nixpkgs one. #17 made that explicit
      # rather than leaving the recipe lying there implying otherwise.
      #
      # Its Package-Requires line (verified in the store source) is
      #   emacs 28.1, projectile 2.5.0, vterm 0.0.2, transient 0.4.0,
      #   markdown-mode 2.5
      # and this package list is hand-maintained, so all four are named below.
      # Nothing resolves dependencies for us here.
      claude-code
      # PROJECTILE IS PLUMBING, NOT A UI CHOICE. It is a hard dependency of 7
      # of claude-code's files: `claude-code-buffer-name' calls
      # `projectile-project-root' and the MCP tools use
      # `projectile-project-files' / `projectile-project-type', neither of
      # which project.el has an analogue for. It is never enabled as a mode
      # and it takes no key: `SPC p' stays project.el's `project-prefix-map'.
      # Do not try to swap it out.
      projectile
      # The terminal Claude actually runs in. Builds a dynamic module, so it
      # is the one package here with a C toolchain behind it.
      vterm
      transient
      # markdown-mode is claude-code's fourth requirement and is already in
      # the language section below -- listed once, there.

      # -- version control --------------------------------------------------
      magit
      forge
      diff-hl

      # -- editing / navigation ---------------------------------------------
      vundo # visualiser over built-in undo; no undo-tree needed
      avy
      envrc # per-buffer direnv, unlike direnv.el's global mutation
      ws-butler # trims only lines you touched

      # -- appearance -------------------------------------------------------
      #
      # gruvbox-theme, NOT doom-themes: doom-themes exists to ship ~60 themes
      # plus Doom-specific extras, and the only one ever loaded here is
      # `doom-gruvbox'. Upstream gruvbox-theme is the same palette from its
      # source -- bg0 #282828, bg1 #3c3836, fg1 #ebdbb2, yellow #fabd2f, green
      # #b8bb26, blue #83a598, purple #d3869b, aqua #8ec07c are identical; only
      # red differs by one digit (#fb4934 upstream, #fb4933 in doom-gruvbox).
      # `gruvbox-dark-medium' is the variant whose bg0 is #282828; hard is
      # #1d2021 and soft is #32302f, so medium is the match, not a preference.
      #
      # WHAT DOES DIFFER, and is accepted: doom-themes carries extra face
      # definitions for magit, org and a handful of other packages that
      # upstream gruvbox does not. Those faces fall back to their package
      # defaults against the same background rather than to nothing, so the
      # loss is polish, not legibility. verify.el asserts the palette so a
      # future theme change is a gate change.
      #
      # `autothemer' is a hard dependency and is PROPAGATED by this
      # derivation (nix-support/propagated-user-env-packages), so it is
      # deliberately not listed -- same convention as org-gcal above.
      gruvbox-theme

      # doom-modeline is NOT a Doom artefact and stays. It is a standalone
      # MELPA package with no dependency on doom-themes or on Doom itself; it
      # only wants nerd-icons, which is listed below.
      doom-modeline
      nerd-icons
      rainbow-delimiters
      hl-todo

      # -- language modes ---------------------------------------------------
      #
      # ONLY the modes Emacs 30.2 does not already ship. 30.2 has a -ts-mode
      # in-tree for bash, c, c++, cmake, csharp, css, dockerfile, elixir, go,
      # go-mod, heex, html, java, js, json, lua, php, python, ruby, rust, toml,
      # tsx, typescript and yaml, so none of those need a package -- they need
      # a grammar (below) and an `auto-mode-alist'/`major-mode-remap-alist'
      # entry (lisp/my-lang.el). It LACKS markdown, haskell, nix, fortran,
      # latex, commonlisp and elisp, which is exactly this list plus the
      # built-in non-ts modes.
      markdown-mode
      haskell-ts-mode # tree-sitter Haskell; calls derived-mode-add-parents
      nix-ts-mode #     tree-sitter Nix;     ditto -- see my-lang.el on eglot
      auctex #          LaTeX. Reaching it needs a shim; see my-lang.el
      sly #             Common Lisp REPL; the modern SLIME fork
      restclient #      .http scratch files, the curl-in-a-buffer workflow

      # -- tree-sitter grammars ---------------------------------------------
      #
      # An EXPLICIT list, not `withAllGrammars'. CLOSURE SIZES, measured with
      # `nix path-info -S' on this build:
      #
      #   these 17 grammars      57.0 MiB   (17 .so files)
      #   with-all-grammars     272.9 MiB   (284 .so files)
      #
      # The bundle derivation itself is a symlink farm and weighs nothing; all
      # of that is the individual grammar store paths in its closure. About
      # 20 MiB of the 57 is a glibc base that Emacs already carries, so the NET
      # effect here is ~+37 MiB against ~+253 MiB -- for ~90 grammars nothing in
      # this config can ever load. treesit only creates a parser for a language
      # some MODE asks for, so a grammar with no corresponding -ts-mode is dead
      # weight in the store, forever.
      #
      # DELIBERATELY ABSENT, and do not "complete" the list by adding them:
      # markdown, latex, commonlisp, elisp and fortran. There is no
      # markdown-ts-mode, latex-ts-mode, commonlisp-ts-mode, elisp-ts-mode or
      # fortran-ts-mode in Emacs 30.2 OR in the packages above -- markdown-mode,
      # AUCTeX, sly, lisp-mode and fortran-mode are all font-lock modes. Adding
      # those grammars would grow the closure and never create a parser.
      #
      # jsdoc is not a mode: javascript-ts-mode and typescript-ts-mode embed it
      # as a range parser for /** */ comments and warn without it.
      (treesit-grammars.with-grammars (g:
        with g; [
          tree-sitter-bash
          tree-sitter-dockerfile
          tree-sitter-go
          tree-sitter-gomod
          tree-sitter-haskell
          tree-sitter-java
          tree-sitter-javascript
          tree-sitter-jsdoc
          tree-sitter-json
          tree-sitter-lua
          tree-sitter-nix
          tree-sitter-python
          tree-sitter-rust
          tree-sitter-toml
          tree-sitter-tsx
          tree-sitter-typescript
          tree-sitter-yaml
        ]))
    ]);
in
  withPkgs.overrideAttrs (old: {
    passthru =
      (old.passthru or {})
      // {
        inherit configDir baseEmacs;
      };
    meta =
      (old.meta or {})
      // {
        description = "Hand-built vanilla Emacs (parallel to the Doom daily driver)";
      };
  })
