// Package theme loads tmux palettes from a JSON file generated by Nix and
// emits the corresponding `set -g` directives. All themes share the same
// shape; switching is just iterating the same field set with different
// hex codes.
package theme

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
)

// Palette mirrors modules/tmux/themes.nix attrset entry-by-entry. Field tags
// must match the JSON keys (camelCase from Nix's toJSON).
type Palette struct {
	PaneBorder            string `json:"paneBorder"`
	PaneActiveBorder      string `json:"paneActiveBorder"`
	MessageFg             string `json:"messageFg"`
	MessageBg             string `json:"messageBg"`
	MessageCommandFg      string `json:"messageCommandFg"`
	MessageCommandBg      string `json:"messageCommandBg"`
	ModeFg                string `json:"modeFg"`
	ModeBg                string `json:"modeBg"`
	StatusFg              string `json:"statusFg"`
	StatusBg              string `json:"statusBg"`
	WindowFg              string `json:"windowFg"`
	WindowBg              string `json:"windowBg"`
	WindowCurrentFg       string `json:"windowCurrentFg"`
	WindowCurrentBg       string `json:"windowCurrentBg"`
	WindowActivityAttr    string `json:"windowActivityAttr"`
	WindowBellFg          string `json:"windowBellFg"`
	WindowBellAttr        string `json:"windowBellAttr"`
	WindowLastFg          string `json:"windowLastFg"`
	StatusLeftPrimaryFg   string `json:"statusLeftPrimaryFg"`
	StatusLeftPrimaryBg   string `json:"statusLeftPrimaryBg"`
	StatusLeftSecondaryFg string `json:"statusLeftSecondaryFg"`
	StatusLeftSecondaryBg string `json:"statusLeftSecondaryBg"`
	StatusRightAccentFg   string `json:"statusRightAccentFg"`
	StatusRightAccentBg   string `json:"statusRightAccentBg"`
	StatusRightAlertFg    string `json:"statusRightAlertFg"`
	StatusRightAlertBg    string `json:"statusRightAlertBg"`
	ClockColor            string `json:"clockColor"`
}

// Themes maps a theme name to its palette.
type Themes map[string]Palette

// Load reads the themes JSON at path.
func Load(path string) (Themes, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read themes: %w", err)
	}
	var t Themes
	if err := json.Unmarshal(data, &t); err != nil {
		return nil, fmt.Errorf("parse themes JSON: %w", err)
	}
	if len(t) == 0 {
		return nil, fmt.Errorf("themes JSON is empty")
	}
	return t, nil
}

// Names returns theme names in stable sort order so cycle behavior is
// deterministic across invocations.
func (t Themes) Names() []string {
	names := make([]string, 0, len(t))
	for n := range t {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// Next returns the theme name after current in sorted order, wrapping at end.
// If current isn't found, returns the first name.
func (t Themes) Next(current string) string {
	names := t.Names()
	for i, n := range names {
		if n == current {
			return names[(i+1)%len(names)]
		}
	}
	return names[0]
}

// SetCommands returns the argv slices to apply the named palette via
// `tmux set-option -g <key> <value>` calls. Each entry is a complete argv.
// helperBin is embedded into status-right's #() substitutions so tmux's
// status-interval refresh always invokes the same binary.
func (t Themes) SetCommands(name, helperBin string) ([][]string, error) {
	p, ok := t[name]
	if !ok {
		return nil, fmt.Errorf("unknown theme: %s", name)
	}
	return paletteCommands(p, helperBin), nil
}

func paletteCommands(p Palette, helperBin string) [][]string {
	style := func(spec string) string { return spec }
	cmds := [][]string{
		{"set-option", "-g", "pane-border-style", style("fg=" + p.PaneBorder)},
		{"set-option", "-g", "pane-active-border-style", style("fg=" + p.PaneActiveBorder)},
		{"set-option", "-g", "message-style", style(fmt.Sprintf("fg=%s,bg=%s,bold", p.MessageFg, p.MessageBg))},
		{"set-option", "-g", "message-command-style", style(fmt.Sprintf("fg=%s,bg=%s,bold", p.MessageCommandFg, p.MessageCommandBg))},
		{"set-window-option", "-g", "mode-style", style(fmt.Sprintf("fg=%s,bg=%s,bold", p.ModeFg, p.ModeBg))},
		{"set-option", "-g", "status-style", style(fmt.Sprintf("fg=%s,bg=%s,none", p.StatusFg, p.StatusBg))},
		{"set-window-option", "-g", "window-status-style", style(fmt.Sprintf("fg=%s,bg=%s,none", p.WindowFg, p.WindowBg))},
		{"set-window-option", "-g", "window-status-current-style", style(fmt.Sprintf("fg=%s,bg=%s,bold", p.WindowCurrentFg, p.WindowCurrentBg))},
		{"set-window-option", "-g", "window-status-activity-style", p.WindowActivityAttr},
		{"set-window-option", "-g", "window-status-bell-style", style(fmt.Sprintf("fg=%s,%s", p.WindowBellFg, p.WindowBellAttr))},
		{"set-window-option", "-g", "window-status-last-style", style(fmt.Sprintf("fg=%s,none", p.WindowLastFg))},
		{"set-window-option", "-g", "clock-mode-colour", p.ClockColor},
	}

	// Status-left and status-right rebuilt from palette segments. Includes
	// the 👓 pairing indicator, ! root indicator (bold,blink), ⌨ prefix, and
	// 🔒 sync indicator -- all from gpakosz parity.
	statusLeft := fmt.Sprintf(
		"#[fg=%s,bg=%s,bold] ❐ #S #[fg=%s,bg=%s,nobold] | #[fg=%s,bg=%s]↑#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m,} ",
		p.StatusLeftPrimaryFg, p.StatusLeftPrimaryBg,
		p.StatusLeftPrimaryBg, p.StatusLeftSecondaryBg,
		p.StatusLeftSecondaryFg, p.StatusLeftSecondaryBg,
	)
	statusRight := fmt.Sprintf(
		"#{?client_prefix,#[fg=%s,bg=%s,bold] ⌨ ,}#{?#{>:#{session_attached},1},#[fg=%s,bg=%s] 👓 ,}#{?pane_synchronized,#[fg=%s,bg=%s] 🔒 ,}#[fg=%s,bg=%s] %%R | %%d %%b | #(%s status user-host #{pane_id} #{pane_pid})#{?#{==:#{user},root},#[bold,blink] !#[default],} ",
		p.StatusRightAlertFg, p.StatusRightAlertBg,
		p.StatusFg, p.StatusBg,
		p.StatusRightAlertFg, p.StatusRightAlertBg,
		p.StatusFg, p.StatusBg,
		helperBin,
	)

	cmds = append(cmds,
		[]string{"set-option", "-g", "status-left", statusLeft},
		[]string{"set-option", "-g", "status-right", statusRight},
	)
	return cmds
}
