// Package theme loads tmux palettes from a JSON file generated by Nix and
// emits the corresponding `set -g` directives. All themes share the same
// shape; switching is just iterating the same field set with different
// hex codes.
package theme

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// Palette mirrors modules/tmux/themes.nix attrset entry-by-entry. Field tags
// must match the JSON keys (camelCase from Nix's toJSON).
type Palette struct {
	PaneBorder            string `json:"paneBorder"`
	PaneActiveBorder      string `json:"paneActiveBorder"`
	MessageFg             string `json:"messageFg"`
	MessageBg             string `json:"messageBg"`
	MessageCommandFg      string `json:"messageCommandFg"`
	MessageCommandBg      string `json:"messageCommandBg"`
	ModeFg                string `json:"modeFg"`
	ModeBg                string `json:"modeBg"`
	StatusFg              string `json:"statusFg"`
	StatusBg              string `json:"statusBg"`
	WindowFg              string `json:"windowFg"`
	WindowBg              string `json:"windowBg"`
	WindowCurrentFg       string `json:"windowCurrentFg"`
	WindowCurrentBg       string `json:"windowCurrentBg"`
	WindowActivityAttr    string `json:"windowActivityAttr"`
	WindowBellFg          string `json:"windowBellFg"`
	WindowBellAttr        string `json:"windowBellAttr"`
	WindowLastFg          string `json:"windowLastFg"`
	StatusLeftPrimaryFg   string `json:"statusLeftPrimaryFg"`
	StatusLeftPrimaryBg   string `json:"statusLeftPrimaryBg"`
	StatusLeftSecondaryFg string `json:"statusLeftSecondaryFg"`
	StatusLeftSecondaryBg string `json:"statusLeftSecondaryBg"`
	StatusLeftTertiaryFg  string `json:"statusLeftTertiaryFg"`
	StatusLeftTertiaryBg  string `json:"statusLeftTertiaryBg"`
	StatusRightAccentFg   string `json:"statusRightAccentFg"`
	StatusRightAccentBg   string `json:"statusRightAccentBg"`
	StatusRightAlertFg    string `json:"statusRightAlertFg"`
	StatusRightAlertBg    string `json:"statusRightAlertBg"`
	ClockColor            string `json:"clockColor"`

	// BatteryGradient is a 4-color anchor list (#rrggbb each) used by the
	// battery heart bar. anchors[0] paints cell 0, anchors[3] paints cell 9;
	// the remaining cells are linearly interpolated in RGB.
	BatteryGradient [4]string `json:"batteryGradient"`
}

// Themes maps a theme name to its palette.
type Themes map[string]Palette

// Load reads the themes JSON at path.
func Load(path string) (Themes, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read themes: %w", err)
	}
	var t Themes
	if err := json.Unmarshal(data, &t); err != nil {
		return nil, fmt.Errorf("parse themes JSON: %w", err)
	}
	if len(t) == 0 {
		return nil, fmt.Errorf("themes JSON is empty")
	}
	return t, nil
}

// Names returns theme names in stable sort order so cycle behavior is
// deterministic across invocations.
func (t Themes) Names() []string {
	names := make([]string, 0, len(t))
	for n := range t {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// Next returns the theme name after current in sorted order, wrapping at end.
// If current isn't found, returns the first name.
func (t Themes) Next(current string) string {
	names := t.Names()
	for i, n := range names {
		if n == current {
			return names[(i+1)%len(names)]
		}
	}
	return names[0]
}

// SetCommands returns the argv slices to apply the named palette via
// `tmux set-option -g <key> <value>` calls. Each entry is a complete argv.
// helperBin is embedded into status-right's #() substitutions so tmux's
// status-interval refresh always invokes the same binary.
func (t Themes) SetCommands(name, helperBin string) ([][]string, error) {
	p, ok := t[name]
	if !ok {
		return nil, fmt.Errorf("unknown theme: %s", name)
	}
	return paletteCommands(p, helperBin), nil
}

func paletteCommands(p Palette, helperBin string) [][]string {
	cmds := [][]string{
		{"set-option", "-g", "pane-border-style", "fg=" + p.PaneBorder},
		{"set-option", "-g", "pane-active-border-style", "fg=" + p.PaneActiveBorder},
		{"set-option", "-g", "message-style", fmt.Sprintf("fg=%s,bg=%s,bold", p.MessageFg, p.MessageBg)},
		{"set-option", "-g", "message-command-style", fmt.Sprintf("fg=%s,bg=%s,bold", p.MessageCommandFg, p.MessageCommandBg)},
		{"set-window-option", "-g", "mode-style", fmt.Sprintf("fg=%s,bg=%s,bold", p.ModeFg, p.ModeBg)},
		{"set-option", "-g", "status-style", fmt.Sprintf("fg=%s,bg=%s,none", p.StatusFg, p.StatusBg)},
		{"set-window-option", "-g", "window-status-style", fmt.Sprintf("fg=%s,bg=%s,none", p.WindowFg, p.WindowBg)},
		{"set-window-option", "-g", "window-status-current-style", fmt.Sprintf("fg=%s,bg=%s,bold", p.WindowCurrentFg, p.WindowCurrentBg)},
		{"set-window-option", "-g", "window-status-activity-style", p.WindowActivityAttr},
		{"set-window-option", "-g", "window-status-bell-style", fmt.Sprintf("fg=%s,%s", p.WindowBellFg, p.WindowBellAttr)},
		{"set-window-option", "-g", "window-status-last-style", fmt.Sprintf("fg=%s,none", p.WindowLastFg)},
		{"set-window-option", "-g", "clock-mode-colour", p.ClockColor},
	}

	// status-left: gpakosz 3-segment fade.
	//   seg1 (Primary, bold): " ❐ #S [git/nix/llm] "
	//   seg2 (Secondary):     " | "  -- thin separator block
	//   seg3 (Tertiary):      " ↑ uptime "
	//
	// tmux expands #{...} formats BEFORE handing the #() job to `sh -c`, so
	// any user-influenceable string (pane_current_path: a hostile directory
	// name from a tarball/clone) must use the #{q:...} quoting modifier or
	// it is shell injection executed on every status refresh.
	statusLeft := fmt.Sprintf(
		`#[fg=%s,bg=%s,bold] ❐ #S#(%s status git-branch #{q:pane_current_path})#(%s status nix-shell)#(%s status llm #{pane_pid}) #[fg=%s,bg=%s,nobold] | #[fg=%s,bg=%s]↑ #(%s status uptime-fmt) `,
		p.StatusLeftPrimaryFg, p.StatusLeftPrimaryBg,
		helperBin, helperBin, helperBin,
		p.StatusLeftSecondaryFg, p.StatusLeftSecondaryBg,
		p.StatusLeftTertiaryFg, p.StatusLeftTertiaryBg,
		helperBin,
	)
	// status-right: 3-segment fade matching gpakosz upstream.
	//   seg1 (StatusFg/Bg, subtle):  battery
	//   seg2 (StatusRightAlert, red): time + date
	//   seg3 (StatusRightAccent, bold): user@host[!]
	// Indicators (prefix/pairing/sync) overlay onto seg1.
	// `#(... status battery)` prints the bar to stdout with embedded
	// `#[fg=colourN]♥` codes; tmux re-scans the substituted output as
	// part of the status-right format pass, so the inline color codes
	// are applied to each heart character. This is the canonical pattern
	// gpakosz/.tmux uses for its battery_bar.
	statusRight := fmt.Sprintf(
		"#{?client_prefix,#[fg=%s,bg=%s,bold] ⌨ ,}#{?session_many_attached,#[fg=%s]#[bg=%s] 👓 ,}#{?pane_synchronized,#[fg=%s]#[bg=%s] 🔒 ,}#[fg=%s,bg=%s,nobold]#(%s status battery) #[fg=%s,bg=%s,nobold] %%R  %%d %%b #[fg=%s,bg=%s,bold] #(%s status user-host #{pane_id} #{pane_pid} #{pid})#{?#{==:#{user},root},#[blink] !,} ",
		p.StatusRightAlertFg, p.StatusRightAlertBg, // prefix indicator (red block, matches 🔒)
		p.StatusFg, p.StatusBg,                     // pairing
		p.StatusRightAlertFg, p.StatusRightAlertBg, // synchronized
		p.StatusFg, p.StatusBg,                     // seg1 (time, battery)
		helperBin,
		p.StatusRightAlertFg, p.StatusRightAlertBg, // seg2 (date)
		p.StatusRightAccentFg, p.StatusRightAccentBg, // seg3 (user-host)
		helperBin,
	)

	cmds = append(cmds,
		[]string{"set-option", "-g", "status-left", statusLeft},
		[]string{"set-option", "-g", "status-right", statusRight},
	)
	return cmds
}

// Interpolate10 returns 10 #rrggbb colors evenly distributed across four
// anchor colors in linear RGB space. Cell 0 is anchors[0]; cell 9 is
// anchors[3]; intermediate cells fall on the line between adjacent anchors.
// Anchors must be #rrggbb literals; malformed entries silently render as
// black for that channel and do not abort the bar.
func Interpolate10(anchors [4]string) [10]string {
	var rgbs [4][3]int
	for i, h := range anchors {
		rgbs[i] = hexToRGB(h)
	}
	var out [10]string
	for i := 0; i < 10; i++ {
		// Map cell index 0..9 onto the 0..3 anchor space.
		t := float64(i) * 3.0 / 9.0
		idx := int(t)
		if idx >= 3 {
			idx = 2
		}
		f := t - float64(idx)
		a := rgbs[idx]
		b := rgbs[idx+1]
		r := int(float64(a[0])*(1-f) + float64(b[0])*f + 0.5)
		g := int(float64(a[1])*(1-f) + float64(b[1])*f + 0.5)
		bl := int(float64(a[2])*(1-f) + float64(b[2])*f + 0.5)
		out[i] = fmt.Sprintf("#%02x%02x%02x", r, g, bl)
	}
	return out
}

func hexToRGB(s string) [3]int {
	s = strings.TrimPrefix(s, "#")
	var rgb [3]int
	_, _ = fmt.Sscanf(s, "%02x%02x%02x", &rgb[0], &rgb[1], &rgb[2])
	return rgb
}

// xterm256Cube is the per-channel value scheme for the 6×6×6 RGB cube at
// xterm color indices 16..231: each channel value picks one of these.
var xterm256Cube = [6]int{0, 95, 135, 175, 215, 255}

// HexTo256 returns the xterm 256-color index closest to the given hex.
// Uses the 6×6×6 RGB cube (indices 16..231) with the standard non-linear
// step values; grayscale (232..255) is not considered. Hex colors are
// emitted as `colourN` strings inside `#(...)` substitution output where
// tmux's format parser swallows literal `#` escapes.
func HexTo256(hex string) int {
	rgb := hexToRGB(hex)
	snap := func(v int) int {
		best, bestDist := 0, 1<<30
		for i, c := range xterm256Cube {
			d := v - c
			if d < 0 {
				d = -d
			}
			if d < bestDist {
				bestDist = d
				best = i
			}
		}
		return best
	}
	return 16 + 36*snap(rgb[0]) + 6*snap(rgb[1]) + snap(rgb[2])
}
